[workspace]
resolver = "2"
members = ["plugins/ai", "plugins/ersatztv", "plugins/jellyfin", "plugins/offair", "plugins/commercialbrainz", "plugins/emergency", "plugins/weather", "plugins/news", "plugins/presets", "plugins/lists", "plugins/local", "plugins/pasttense"]

[profile.release]
lto = "thin"
strip = true